final List<String> allQuotes = [
  "Every day is a new beginning.",
  "You are capable of amazing things.",
  "Believe you can and you're halfway there.",
  "Small steps still move you forward.",
  "Your potential is endless.",
  "Progress, not perfection.",
  "Be the reason someone smiles today.",
  "Challenges are opportunities in disguise.",
  "You grow through what you go through.",
  "Today is your opportunity to build tomorrow.",
  "Dream big, start small, act now.",
  "You are stronger than you think.",
  "Positivity always wins.",
  "Make today so awesome yesterday gets jealous.",
  "The only limit is the one you set yourself.",
  "Rise up, start fresh, embrace the new journey.",
  "Be so good they can't ignore you.",
  "Every moment is a fresh beginning.",
  "You are the artist of your own life.",
  "Kindness is always in style.",
  "Do what you can, with what you have, where you are.",
  "Your vibe attracts your tribe.",
  "The best way to predict the future is to create it.",
  "Be the change you wish to see.",
  "Gratitude turns what we have into enough.",
  "You're never too old to set another goal.",
  "Mistakes are proof you're trying.",
  "The secret of getting ahead is getting started.",
  "You are enough just as you are.",
  "Today's efforts are tomorrow's successes.",
  "Surround yourself with those who lift you higher.",
  "Every accomplishment starts with the decision to try.",
  "Happiness is an inside job.",
  "Let your light shine brightly.",
  "The only way to do great work is to love what you do.",
  "You have within you right now everything you need.",
  "Turn your wounds into wisdom.",
  "Be fearless in the pursuit of what sets your soul on fire.",
  "Success is the sum of small efforts repeated daily.",
  "What you seek is seeking you.",
  "No rain, no flowers.",
  "Your current situation is not your final destination.",
  "The harder you work for something, the greater you'll feel when you achieve it.",
  "Start where you are. Use what you have. Do what you can.",
  "Every day may not be good, but there's something good in every day.",
  "You become what you believe.",
  "The best project you'll ever work on is you.",
  "Don't watch the clock; do what it does. Keep going.",
  "What lies behind you and what lies before you are tiny matters compared to what lies within you.",
  "You don't have to be perfect to be amazing.",
  "The only time you should ever look back is to see how far you've come.",
  "Opportunities don't happen, you create them.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Don't stop until you're proud.",
  "Be so busy loving your life that you have no time for hate or worry.",
  "The expert in anything was once a beginner.",
  "Your attitude determines your direction.",
  "Dream without fear. Love without limits.",
  "The only person you should try to be better than is the person you were yesterday.",
  "Difficult roads often lead to beautiful destinations.",
  "When you focus on the good, the good gets better.",
  "You were given this life because you're strong enough to live it.",
  "Do more of what makes you happy.",
  "Create a life you're excited to wake up to.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Be the energy you want to attract.",
  "Great things never come from comfort zones.",
  "Don't let yesterday take up too much of today.",
  "You're braver than you believe, stronger than you seem, and smarter than you think.",
  "Every sunset is an opportunity to reset.",
  "The best view comes after the hardest climb.",
  "Don't count the days, make the days count.",
  "Your speed doesn't matter. Forward is forward.",
  "The only way to achieve the impossible is to believe it's possible.",
  "You don't find the happy life. You make it.",
  "Success is liking yourself, liking what you do, and liking how you do it.",
  "Tough times never last, but tough people do.",
  "The more you praise and celebrate your life, the more there is to celebrate.",
  "You are never too old to set another goal or dream a new dream.",
  "The moment you're ready to quit is usually the moment right before the miracle happens.",
  "You can't go back and change the beginning, but you can start where you are and change the ending.",
  "The pain you feel today will be the strength you feel tomorrow.",
  "If opportunity doesn't knock, build a door.",
  "Your value doesn't decrease based on someone's inability to see your worth.",
  "Keep your face always toward the sunshine—and shadows will fall behind you.",
  "The only thing standing between you and your goal is the story you keep telling yourself.",
  "Fall seven times, stand up eight.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "Don't let small minds convince you that your dreams are too big.",
  "The best revenge is massive success.",
  "You must do the things you think you cannot do.",
  "It always seems impossible until it's done.",
  "If you're offered a seat on a rocket ship, don't ask what seat! Just get on.",
  "The biggest risk is not taking any risk.",
  "The only place where success comes before work is in the dictionary.",
  "Don't be pushed by your problems. Be led by your dreams.",
  "Success isn't about how much money you make, it's about the difference you make.",
  "The way to get started is to quit talking and begin doing.",
  "If you can dream it, you can do it.",
  "The future depends on what you do today.",
  "Life is 10% what happens to us and 90% how we react to it.",
  "Whatever you are, be a good one.",
  "The secret to getting ahead is getting started.",
  "Don't watch the clock; do what it does. Keep going.",
  "You miss 100% of the shots you don't take.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "Our greatest glory is not in never falling, but in rising every time we fall.",
  "Everything you've ever wanted is on the other side of fear.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "What we think, we become.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Life is what happens when you're busy making other plans.",
  "Twenty years from now you will be more disappointed by the things you didn't do than by the ones you did do.",
  "To live is the rarest thing in the world. Most people exist, that is all.",
  "You can't use up creativity. The more you use, the more you have.",
  "Do not go where the path may lead, go instead where there is no path and leave a trail.",
  "Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it.",
  "The two most important days in your life are the day you are born and the day you find out why.",
  "Your time is limited, don't waste it living someone else's life.",
  "Strive not to be a success, but rather to be of value.",
  "I find that the harder I work, the more luck I seem to have.",
  "The only thing worse than starting something and failing is not starting something.",
  "If you want to lift yourself up, lift up someone else.",
  "A person who never made a mistake never tried anything new.",
  "The person who says it cannot be done should not interrupt the person doing it.",
  "You don't have to see the whole staircase, just take the first step.",
  "Act as if what you do makes a difference. It does.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "The mind is everything. What you think you become.",
  "The best way out is always through.",
  "I can't change the direction of the wind, but I can adjust my sails to always reach my destination.",
  "Believe in yourself and all that you are. Know that there is something inside you greater than any obstacle.",
  "Too many of us are not living our dreams because we are living our fears.",
  "Challenges are what make life interesting and overcoming them is what makes life meaningful.",
  "If you want to live a happy life, tie it to a goal, not to people or things.",
  "Just when the caterpillar thought the world was ending, it became a butterfly.",
  "We may encounter many defeats but we must not be defeated.",
  "My mission in life is not merely to survive, but to thrive.",
  "Life shrinks or expands in proportion to one's courage.",
  "You can't cross the sea merely by standing and staring at the water.",
  "What you do today can improve all your tomorrows.",
  "The only true wisdom is in knowing you know nothing.",
  "The journey of a thousand miles begins with one step.",
  "Don't be afraid to give up the good to go for the great.",
  "You are never too old to set another goal or to dream a new dream.",
  "If you're not making mistakes, then you're not making decisions.",
  "The difference between ordinary and extraordinary is that little extra.",
  "The best dreams happen when you're awake.",
  "The only way to discover the limits of the possible is to go beyond them into the impossible.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "In the middle of difficulty lies opportunity.",
  "It does not matter how slowly you go as long as you do not stop.",
  "Quality is not an act, it is a habit.",
  "The successful warrior is the average person, with laser-like focus.",
  "There is no substitute for hard work.",
  "First they ignore you, then they laugh at you, then they fight you, then you win.",
  "The only place success comes before work is in the dictionary.",
  "Either you run the day or the day runs you.",
  "I am not a product of my circumstances. I am a product of my decisions.",
  "The more you praise and celebrate your life, the more there is in life to celebrate.",
  "You can't build a reputation on what you are going to do.",
  "It is never too late to be what you might have been.",
  "Change your thoughts and you change your world.",
  "The only person you are destined to become is the person you decide to be.",
  "Everything has beauty, but not everyone sees it.",
  "How wonderful it is that nobody need wait a single moment before starting to improve the world.",
  "The power of imagination makes us infinite.",
  "Do not let what you cannot do interfere with what you can do.",
  "Success is the sum of small efforts, repeated day in and day out.",
  "The best preparation for tomorrow is doing your best today.",
  "Happiness is not something ready made. It comes from your own actions.",
  "Keep your eyes on the stars, and your feet on the ground.",
  "The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.",
  "You are always one decision away from a totally different life.",
  "What seems to us as bitter trials are often blessings in disguise.",
  "The difference between who you are and who you want to be is what you do.",
  "The real opportunity for success lies within the person and not in the job.",
  "If you don't design your own life plan, chances are you'll fall into someone else's plan.",
  "To accomplish great things, we must not only act, but also dream; not only plan, but also believe.",
  "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence.",
  "You can't fall if you don't climb. But there's no joy in living your whole life on the ground.",
  "Believe in yourself, take on your challenges, dig deep within yourself to conquer fears.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "You may be disappointed if you fail, but you are doomed if you don't try.",
  "The only way to do great work is to love what you do.",
  "If you want to achieve greatness stop asking for permission.",
  "Things work out best for those who make the best of how things work out.",
  "Today's accomplishments were yesterday's impossibilities.",
  "The distance between your dreams and reality is called action.",
  "If you can imagine it, you can achieve it. If you can dream it, you can become it.",
  "Action is the foundational key to all success.",
  "The secret to success is to know something nobody else knows.",
  "Don't be afraid to give up the good to go for the great.",
  "Success usually comes to those who are too busy to be looking for it.",
  "You don't have to be great to start, but you have to start to be great.",
  "The only place where your dream becomes impossible is in your own thinking.",
  "The future belongs to those who prepare for it today.",
  "The expert in anything was once a beginner.",
  "Work hard in silence, let your success be your noise.",
  "Don't let the fear of losing be greater than the excitement of winning.",
  "Successful people do what unsuccessful people are not willing to do.",
  "There are no shortcuts to any place worth going.",
  "The only impossible journey is the one you never begin.",
  "Some people dream of success while others wake up and work for it.",
  "The only thing worse than starting something and failing is not starting something.",
  "The road to success and the road to failure are almost exactly the same.",
  "Success is getting what you want. Happiness is wanting what you get.",
  "Don't aim for success if you want it; just do what you love and believe in, and it will come naturally.",
  "The successful person is the one who finds out what is the matter with their business before it finds out what is the matter with them.",
  "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.",
  "Success is not in what you have, but who you are.",
  "I never dreamed about success. I worked for it.",
  "Success is not just about making money. It's about making a difference.",
  "The secret of success is to do the common things uncommonly well.",
  "Success isn't about being the best. It's about always getting better.",
  "The successful warrior is the average person, with laser-like focus.",
  "Success is the sum of small efforts, repeated day in and day out.",
  "Success is not the key to happiness. Happiness is the key to success.",
  "Formal education will make you a living; self-education will make you a fortune.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "The difference between a successful person and others is not lack of strength, not lack of knowledge, but rather lack of will.",
  "The secret to success is to know something nobody else knows.",
  "Success is not the absence of failure; it's the persistence through failure.",
  "Success seems to be connected with action. Successful people keep moving.",
  "Success is simple. Do what's right, the right way, at the right time.",
  "The price of success is hard work, dedication to the job at hand.",
  "Success is where preparation and opportunity meet.",
  "Success is doing ordinary things extraordinarily well.",
  "Success is a state of mind. If you want success, start thinking of yourself as a success.",
  "Success is not in never falling, but in rising every time we fall.",
  "Success is not measured by what you accomplish, but by the opposition you have encountered.",
  "Success is getting what you want. Happiness is wanting what you get.",
  "Success is the progressive realization of a worthy goal or ideal.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "Success is liking yourself, liking what you do, and liking how you do it.",
  "Success is not about the destination, but about the journey.",
  "Success is the ability to go from one failure to another with no loss of enthusiasm.",
  "Success is not how high you have climbed, but how you make a positive difference to the world.",
  "Success is the maximum utilization of the ability that you have.",
  "Success is peace of mind which is a direct result of self-satisfaction.",
  "Success is not about being better than someone else, it's about being better than you used to be.",
  "Success is the freedom to be who you really are.",
  "Success is not about luck, it's about labor.",
  "Success is not about possessions, it's about perceptions.",
  "Success is not about popularity, it's about personality.",
  "Success is not about perfection, it's about progression.",
  "Success is not about position, it's about passion.",
  "Success is not about power, it's about purpose.",
  "Success is not about prestige, it's about principles.",
  "Success is not about prominence, it's about productivity.",
  "Success is not about prosperity, it's about perspective.",
  "Success is not about publicity, it's about performance.",
  "Success is not about quantity, it's about quality.",
  "Success is not about recognition, it's about resilience.",
  "Success is not about status, it's about service.",
  "Success is not about supremacy, it's about sincerity.",
  "Success is not about talent, it's about tenacity.",
  "Success is not about wealth, it's about wellness.",
  "Success is not about winning, it's about wisdom.",
  "Success is not about words, it's about works.",
  "Success is not about yesterday, it's about today.",
  "Success is not about you, it's about others.",
  "Success is not accidental, it's intentional.",
  "Success is not an act, it's a habit.",
  "Success is not given, it's earned.",
  "Success is not inherited, it's created.",
  "Success is not luck, it's labor.",
  "Success is not magic, it's method.",
  "Success is not measured by money, but by meaning.",
  "Success is not owned, it's leased, and rent is due every day.",
  "Success is not random, it's relational.",
  "Success is not received, it's achieved.",
  "Success is not static, it's strategic.",
  "Success is not the destination, it's the direction.",
  "Success is not the key to happiness. Happiness is the key to success.",
  "Success is not what you have, but who you are.",
  "Success is nothing more than a few simple disciplines, practiced every day.",
  "Success is often achieved by those who don't know that failure is inevitable.",
  "Success is simple. Do what's right, the right way, at the right time.",
  "Success is the ability to go from failure to failure without losing your enthusiasm.",
  "Success is the progressive realization of a worthy goal or ideal.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "Success isn't about how much money you make, it's about the difference you make.",
  "Success seems to be connected with action. Successful people keep moving.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Successful people do what unsuccessful people are not willing to do.",
  "Successful people have fear, successful people have doubts, and successful people have worries.",
  "The difference between a successful person and others is not lack of strength, not lack of knowledge, but rather lack of will.",
  "The difference between who you are and who you want to be is what you do.",
  "The key to success is to focus on goals, not obstacles.",
  "The only place where success comes before work is in the dictionary.",
  "The road to success is always under construction.",
  "The secret of success is to do the common things uncommonly well.",
  "The secret to success is to know something nobody else knows.",
  "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.",
  "To succeed in life, you need two things: ignorance and confidence.",
  "True success is overcoming the fear of being unsuccessful.",
  "What's the secret to success? Right decisions. How do you make right decisions? Experience.",
  "Without hard work, nothing grows but weeds.",
  "You don't have to be great to start, but you have to start to be great.",
  "Your positive action combined with positive thinking results in success.",
  "Success is not about being the best. It's about being better than you were yesterday.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "What you do today can improve all your tomorrows.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Don't watch the clock; do what it does. Keep going.",
  "The only way to do great work is to love what you do.",
  "Success is the sum of small efforts, repeated day in and day out.",
  "Believe you can and you're halfway there.",
  "The best way to predict your future is to create it.",
  "You are never too old to set another goal or to dream a new dream.",
  "Act as if what you do makes a difference. It does.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "The only place where your dream becomes impossible is in your own thinking.",
  "You don't have to be perfect to be amazing.",
  "The expert in anything was once a beginner.",
  "Dream big and dare to fail.",
  "Your attitude, not your aptitude, will determine your altitude.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "The best revenge is massive success.",
  "Success is liking yourself, liking what you do, and liking how you do it.",
  "The only thing standing between you and your goal is the story you keep telling yourself.",
  "Success is not the key to happiness. Happiness is the key to success.",
  "The harder you work for something, the greater you'll feel when you achieve it.",
  "Don't stop when you're tired. Stop when you're done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Do something today that your future self will thank you for.",
  "Little things make big days.",
  "It's going to be hard, but hard does not mean impossible.",
  "Don't wait for opportunity. Create it.",
  "Sometimes we're tested not to show our weaknesses, but to discover our strengths.",
  "The key to success is to start before you're ready.",
  "Don't dream your life, live your dream.",
  "Dream it. Believe it. Build it.",
  "Success is what happens after you stop making excuses.",
  "Make each day your masterpiece.",
  "Hustle until your haters ask if you're hiring.",
  "The only way to achieve the impossible is to believe it is possible.",
  "Work hard in silence. Let success make the noise.",
  "Failure is the opportunity to begin again more intelligently.",
  "Your life does not get better by chance, it gets better by change.",
  "Strive for progress, not perfection.",
  "Success is the best revenge.",
  "The pain you feel today will be the strength you feel tomorrow.",
  "The only bad workout is the one that didn't happen.",
  "Discipline is choosing between what you want now and what you want most.",
  "You were born to be real, not to be perfect.",
  "The secret of getting ahead is getting started.",
  "You can't go back and change the beginning, but you can start where you are and change the ending.",
  "It's not about having time, it's about making time.",
  "The moment you're ready to quit is usually the moment right before the miracle happens.",
  "Don't limit your challenges. Challenge your limits.",
  "Every day is a second chance.",
  "Turn your cant's into cans and your dreams into plans.",
  "You don't get what you wish for. You get what you work for.",
  "Little by little, a little becomes a lot.",
  "The only difference between ordinary and extraordinary is that little extra.",
  "Success is a journey, not a destination.",
  "Be so good they can't ignore you.",
  "The comeback is always stronger than the setback.",
  "Dream without limits. Live with purpose.",
  "You are the only one who can limit your greatness.",
  "The only failure is not trying.",
  "Your speed doesn't matter. Forward is forward.",
  "The best way to get started is to quit talking and begin doing.",
  "The only person you should try to be better than is the person you were yesterday.",
  "You miss 100% of the shots you don't take.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "Don't let yesterday take up too much of today.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "You may be disappointed if you fail, but you are doomed if you don't try.",
  "The only way to do great work is to love what you do.",
  "If you want to achieve greatness stop asking for permission.",
  "Things work out best for those who make the best of how things work out.",
  "Today's accomplishments were yesterday's impossibilities.",
  "The distance between your dreams and reality is called action.",
  "If you can imagine it, you can achieve it. If you can dream it, you can become it.",
  "Action is the foundational key to all success.",
  "The secret to success is to know something nobody else knows.",
  "Don't be afraid to give up the good to go for the great.",
  "Success usually comes to those who are too busy to be looking for it.",
  "You don't have to be great to start, but you have to start to be great.",
  "The only place where your dream becomes impossible is in your own thinking.",
  "The future belongs to those who prepare for it today.",
  "The expert in anything was once a beginner.",
  "Work hard in silence, let your success be your noise.",
  "Don't let the fear of losing be greater than the excitement of winning.",
  "Successful people do what unsuccessful people are not willing to do.",
  "There are no shortcuts to any place worth going.",
  "The only impossible journey is the one you never begin.",
  "Some people dream of success while others wake up and work for it.",
  "The only thing worse than starting something and failing is not starting something.",
  "The road to success and the road to failure are almost exactly the same.",
  "Success is getting what you want. Happiness is wanting what you get.",
  "Don't aim for success if you want it; just do what you love and believe in, and it will come naturally.",
  "The successful person is the one who finds out what is the matter with their business before it finds out what is the matter with them.",
  "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.",
  "Success is not in what you have, but who you are.",
  "I never dreamed about success. I worked for it.",
  "Success is not just about making money. It's about making a difference.",
  "The secret of success is to do the common things uncommonly well.",
  "Success isn't about being the best. It's about always getting better.",
  "The successful warrior is the average person, with laser-like focus.",
  "Success is the sum of small efforts, repeated day in and day out.",
  "Success is not the key to happiness. Happiness is the key to success.",
  "Formal education will make you a living; self-education will make you a fortune.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "The difference between a successful person and others is not lack of strength, not lack of knowledge, but rather lack of will.",
  "The secret to success is to know something nobody else knows.",
  "Success is not the absence of failure; it's the persistence through failure.",
  "Success seems to be connected with action. Successful people keep moving.",
  "Success is simple. Do what's right, the right way, at the right time.",
  "The price of success is hard work, dedication to the job at hand.",
  "Success is where preparation and opportunity meet.",
  "Success is doing ordinary things extraordinarily well.",
  "Success is a state of mind. If you want success, start thinking of yourself as a success.",
  "Success is not in never falling, but in rising every time we fall.",
  "Success is not measured by what you accomplish, but by the opposition you have encountered.",
  "Success is getting what you want. Happiness is wanting what you get.",
  "Success is the progressive realization of a worthy goal or ideal.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "Success is liking yourself, liking what you do, and liking how you do it.",
  "Success is not about the destination, but about the journey.",
  "Success is the ability to go from one failure to another with no loss of enthusiasm.",
  "Success is not how high you have climbed, but how you make a positive difference to the world.",
  "Success is the maximum utilization of the ability that you have.",
  "Success is peace of mind which is a direct result of self-satisfaction.",
  "Success is not about being better than someone else, it's about being better than you used to be.",
  "Success is the freedom to be who you really are.",
  "Success is not about luck, it's about labor.",
  "Success is not about possessions, it's about perceptions.",
  "Success is not about popularity, it's about personality.",
  "Success is not about perfection, it's about progression.",
  "Success is not about position, it's about passion.",
  "Success is not about power, it's about purpose.",
  "Success is not about prestige, it's about principles.",
  "Success is not about prominence, it's about productivity.",
  "Success is not about prosperity, it's about perspective.",
  "Success is not about publicity, it's about performance.",
  "Success is not about quantity, it's about quality.",
  "Success is not about recognition, it's about resilience.",
  "Success is not about status, it's about service.",
  "Success is not about supremacy, it's about sincerity.",
  "Success is not about talent, it's about tenacity.",
  "Success is not about wealth, it's about wellness.",
  "Success is not about winning, it's about wisdom.",
  "Success is not about words, it's about works.",
  "Success is not about yesterday, it's about today.",
  "Success is not about you, it's about others.",
  "Success is not accidental, it's intentional.",
  "Success is not an act, it's a habit.",
  "Success is not given, it's earned.",
  "Success is not inherited, it's created.",
  "Success is not luck, it's labor.",
  "Success is not magic, it's method.",
  "Success is not measured by money, but by meaning.",
  "Success is not owned, it's leased, and rent is due every day.",
  "Success is not random, it's relational.",
  "Success is not received, it's achieved.",
  "Success is not static, it's strategic.",
  "Success is not the destination, it's the direction.",
  "Success is not the key to happiness. Happiness is the key to success.",
  "Success is not what you have, but who you are.",
  "Success is nothing more than a few simple disciplines, practiced every day.",
  "Success is often achieved by those who don't know that failure is inevitable.",
  "Success is simple. Do what's right, the right way, at the right time.",
  "Success is the ability to go from failure to failure without losing your enthusiasm.",
  "Success is the progressive realization of a worthy goal or ideal.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "Success isn't about how much money you make, it's about the difference you make.",
  "Success seems to be connected with action. Successful people keep moving.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Successful people do what unsuccessful people are not willing to do.",
  "Successful people have fear, successful people have doubts, and successful people have worries.",
  "The difference between a successful person and others is not lack of strength, not lack of knowledge, but rather lack of will.",
  "The difference between who you are and who you want to be is what you do.",
  "The key to success is to focus on goals, not obstacles.",
  "The only place where success comes before work is in the dictionary.",
  "The road to success is always under construction.",
  "The secret of success is to do the common things uncommonly well.",
  "The secret to success is to know something nobody else knows.",
  "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.",
  "To succeed in life, you need two things: ignorance and confidence.",
  "True success is overcoming the fear of being unsuccessful.",
  "What's the secret to success? Right decisions. How do you make right decisions? Experience.",
  "Without hard work, nothing grows but weeds.",
  "You don't have to be great to start, but you have to start to be great.",
  "Your positive action combined with positive thinking results in success."
];